name: Run Postman Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman and reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman tests
        run: |
          newman run tests/collection.json \
            -r htmlextra \
            --reporter-htmlextra-export report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-report
          path: report.html
